---
- name: Include optional user and group creation.
  when: (es_user_id is defined) and (es_group_id is defined)
  include: elasticsearch-optional-user.yml

- name: force_install=no
  set_fact: force_install=no

- name: force_install=yes when es_allow_downgrades
  set_fact: force_install=yes
  when: es_allow_downgrades

- name: Install apt-transport-https to support https APT downloads
  apt: name=apt-transport-https state=present
  when: es_use_repository

- name: Add Elasticsearch repository key
  apt_key: url="{{ es_apt_key }}" state=present
  when: es_use_repository and es_apt_key

- name: Add elasticsearch repository
  apt_repository: repo={{ item.repo }} state={{ item.state}}
  with_items:
    - { repo: "{{ es_apt_url_old }}", state: "absent" }
    - { repo: "{{ es_apt_url }}", state: "present" }
  when: es_use_repository

- name: Include version lock
  include: elasticsearch-version-lock.yml
  when: es_version_lock

- name: Ensure elasticsearch is installed
  apt: name=elasticsearch{% if es_version is defined and es_version != "" %}={{ es_version }}{% endif %} state=present force={{force_install}} allow_unauthenticated={{ 'no' if es_apt_key else 'yes' }} cache_valid_time=86400
  when: es_use_repository
  register: debian_elasticsearch_install_from_repo

- name: Download elasticsearch from url
  get_url: url={% if es_custom_package_url is defined %}{{ es_custom_package_url }}{% else %}{{ es_package_url }}-{{ es_version }}.deb{% endif %} dest=/tmp/elasticsearch-{{ es_version }}.deb validate_certs=no
  when: not es_use_repository

- name: Ensure elasticsearch is installed from downloaded package
  apt: deb=/tmp/elasticsearch-{{ es_version }}.deb
  when: not es_use_repository
  register: elasticsearch_install_from_package
