---
- name: Add Docker key
  apt_key: keyserver=p80.pool.sks-keyservers.net id=58118E89F3A912897C070ADBF76221572C52609D
  become: yes
  become_method: sudo

- name: Add Docker repository
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present
  become: yes
  become_method: sudo

- name: Update Apt and Install docker-engine
  apt: update_cache=yes name=docker-engine state=latest
  become: yes
  become_method: sudo

- name: Install pip
  apt: name=python-pip state=present
  become: yes
  become_method: sudo

- name: Start docker-engine
  service: name=docker state=started
  become: yes
  become_method: sudo

- name: set maximum map count in sysctl/systemd (need to run elasticsearch docker image)
  become: true
  sysctl: name=vm.max_map_count value={{ os_max_map_count }} state=present





