---
- name: Format jenkins disk
  filesystem:
    fstype: ext4
    dev: "{{ jenkins_disk }}"
  become: yes
  become_method: sudo

- name: Mount jenkins disk
  mount:
    name: /var/lib/jenkins/
    src: "{{ jenkins_disk }}"
    fstype: ext4
    state: mounted

- name: Format docker disk
  filesystem:
    fstype: ext4
    dev: "{{ docker_disk }}"
  become: yes
  become_method: sudo

- name: Mount docker disk
  mount:
    name: /var/lib/docker/
    src: "{{ docker_disk }}"
    fstype: ext4
    state: mounted
